### PR TITLE
references: add offset to pull

### PR DESCRIPTION
**Pull request by Fishrock123**
Refs: https://github.com/Fishrock123/bob/issues/23

### CODE REVIEW

**Review by jasnell — APPROVED** [review]

**Comment by Raynos** [comment]
If you add an offset to `pull()` it makes sense to also add an `offset` to `next()`

**Comment by Fishrock123** [comment]
@Raynos You mean to note where that particular read was done from?

**Comment by Raynos** [comment]
Correct, to note at which offset the n `bytes` where read into the buffer.

But this raises a good question, what does `offset` on `pull()` mean ? the `offset` to read into in the `buffer` or the `offset` to read from in whatever the source is ( like an offset in a file on disk ).

**Comment by Fishrock123** [comment]
It was supposed to be source read location. I am still not really sure this fits well into the stream abstraction...

**Comment by Raynos** [comment]
Closing out due to lack of activity.

**Pull request closed without merging**
